### ISSUE TITLE
HOW LONG HAS LAKE ONTARIO BEEN MISSING? @#$%

### ISSUE THREAD

**Issue by almccon** [stamen/toner-carto#20]
It disappears at zoom 8 and smaller. So it's gone or corrupted or mistagged in our OSM extract. @mojodna @bdon Has this been missing all along and we just haven't noticed it?!

![screen shot 2014-11-12 at 5 47 59 pm](https://cloud.githubusercontent.com/assets/1212178/5022092/65298d7c-6a94-11e4-9f1d-b9a993407be1.png)

New rule I'm imposing on myself: check every Great Lake at every zoom level every time we deploy.

**Comment by fche** [comment]
As observed on the tile.openstreetmap.org servers, at zoom level 5, Lake Ontario is still/again missing:

http://c.tile.openstreetmap.org/5/8/11.png
http://c.tile.openstreetmap.org/5/9/11.png

**Comment by almccon** [comment]
@fche Thanks for the comment. This repo is for the Toner map (http://maps.stamen.com/toner), and right now Lake Ontario is _not_ missing on Toner. That's why this issue is closed.

You are correct that Lake Ontario is missing on the OSM default style. There is a separate repo for that style, and they already have an issue open for that problem: https://github.com/gravitystorm/openstreetmap-carto/issues/1604
