### ISSUE TITLE
Error when trying to run 'make'

### ISSUE THREAD

**Issue by jbcima** [stamen/toner-carto#36]
Can't make toner properly.
![screen shot 2015-07-20 at 11 03 25 am](https://cloud.githubusercontent.com/assets/2835740/8779023/16ef56b4-2ecf-11e5-80d8-5393a6ad9d3d.png)

**Comment by mojodna** [comment]
You should import an extract first (it doesn't make any assumptions about where you want to show).  https://github.com/stamen/toner-carto/blob/master/Makefile#L174-L184 has a list of pre-configured extracts (though I think the SF URL is wrong).  `make db/seattle` to import Seattle, for example.

This deserves a better error message.

**Comment by jbcima** [comment]
ah ok. I'm personally just interested in creating a US map with state lines
and state labels. Is there a way to just do this without working with this
data?

If I import an extract of Seattle for instance, then create toner-labels
will I receive this result? I'll try it later.

On Monday, July 20, 2015, Seth Fitzsimmons <notifications@github.com> wrote:

> You should import an extract first (it doesn't make any assumptions about
> where you want to show).
> https://github.com/stamen/toner-carto/blob/master/Makefile#L174-L184 has
> a list of pre-configured extracts (though I think the SF URL is wrong). make
> db/seattle to import Seattle, for example.
>
> This deserves a better error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/toner-carto/issues/36#issuecomment-122916328>.
>


-- 
Regards,
Jeremy Cimafonte
web. http://www.jeremycimafonte.com
tel. +1(908)463-4387

**Comment by mojodna** [comment]
You might be able to get away with just the data from http://www.naturalearthdata.com/downloads/10m-cultural-vectors/ (though you'd need to handle the styling somehow).

You're right though, if you import a tiny extract it'll load quickly and you'll get natural earth at low zooms providing most of what you're looking for (with a few tweaks, probably what you want).

**Comment by jbcima** [comment]
hi, when i try to run make db/seattle 

pq: database "toner" does not exist
make: *** [db/osm-seattle] Error 1

isnt that supposed to create the database as well?

**Comment by mojodna** [comment]
Yes, though it's possible that it doesn't have permission.  Try running `createdb toner` to create it manually.

**Comment by jbcima** [comment]
yep, i already did that but now:
SQL Error: pq: function addgeometrycolumn(unknown, unknown, unknown, unknown, unknown, integer) does not exist in query SELECT AddGeometryColumn('import', 'osm_stations', 'geometry', '3857', 'POINT', 2);
make: *** [db/osm-seattle] Error 1

**Comment by mojodna** [comment]
`psql -d toner -c "create extension postgis"`?  If that succeeds, you'll also need the `hstore` extension.

That could also be an artifact from highroad being built for PostGIS 1.5 (though it has worked for me on 2.1).

**Comment by jbcima** [comment]
even with running make db/seattle i still get the same error:
[INFO] Imposm took: 1m17.630776761s
psql:sql/functions/highroad.sql:1: NOTICE:  view "highroad_z15plus" does not exist, skipping
psql:sql/functions/highroad.sql:2: NOTICE:  view "highroad_z14" does not exist, skipping
psql:sql/functions/highroad.sql:3: NOTICE:  view "highroad_z13" does not exist, skipping
psql:sql/functions/highroad.sql:4: NOTICE:  view "highroad_z12" does not exist, skipping
psql:sql/functions/highroad.sql:5: NOTICE:  view "highroad_z11" does not exist, skipping
psql:sql/functions/highroad.sql:6: NOTICE:  view "highroad_z10" does not exist, skipping
psql:sql/functions/highroad.sql:26: ERROR:  relation "osm_planet_osm_line_z10" does not exist
LINE 18:       FROM osm_planet_osm_line_z10
                    ^
make: *** [db/functions/highroad] Error 3

how do i just nip it in the but and fix it? Thanks!

**Comment by mojodna** [comment]
`imposm3` should create `osm_planet_osm_line_z10` as one of its generalizations...

What tables / views are in your db?  Did `imposm3` finish successfully?

**Comment by jbcima** [comment]
it appears to be there and filled.

toner-# \dt
                 List of relations
 Schema |          Name           | Type  | Owner
--------+-------------------------+-------+--------
 public | osm_admin               | table | jbcima
 public | osm_aeroways            | table | jbcima
 public | osm_brown_areas         | table | jbcima
 public | osm_brown_areas_z10     | table | jbcima
 public | osm_brown_areas_z13     | table | jbcima
 public | osm_buildings           | table | jbcima
 public | osm_buildings_z13       | table | jbcima
 public | osm_green_areas         | table | jbcima
 public | osm_green_areas_z10     | table | jbcima
 public | osm_green_areas_z13     | table | jbcima
 public | osm_planet_osm_line_z10 | table | jbcima
 public | osm_planet_osm_line_z11 | table | jbcima
 public | osm_planet_osm_line_z12 | table | jbcima
 public | osm_planet_osm_line_z13 | table | jbcima
 public | osm_planet_osm_line_z14 | table | jbcima
 public | osm_roads               | table | jbcima
 public | osm_stations            | table | jbcima
 public | osm_water_areas         | table | jbcima
 public | osm_water_areas_z10     | table | jbcima
 public | osm_water_areas_z13     | table | jbcima
 public | spatial_ref_sys         | table | jbcima
(21 rows)

**Comment by mojodna** [comment]
2 things to try:

1) Edit [line 55](https://github.com/stamen/toner-carto/blob/master/Makefile#L55) so that it looks like this (the spaces are a tab character) and re-run `make` (I want to ensure that `PGDATABASE` is set):

```Makefile
default: toner
	env | grep PG
```

2) run `make .env` (if you haven't already)

I think https://github.com/stamen/toner-carto/commit/ab49c3f81330a0a4599b140a08974cc4e2acd0dc may have broken things when I attempted to provide a default w/o requiring `.env`.

**Comment by jbcima** [comment]
thanks so much. pretty sure it was the 'make .env' that did the trick.

i don't see streets when i zoom in? which is fine this works for me. Quite
likely if i cleared out the db, cloned the repo again, ran 'make .env', i
would get the OSM street-level data as well.

On Mon, Jul 20, 2015 at 9:24 PM, Seth Fitzsimmons <notifications@github.com>
wrote:

> 2 things to try:
>
> 1) Edit line 55
> <https://github.com/stamen/toner-carto/blob/master/Makefile#L55> so that
> it looks like this (the spaces are a tab character) and re-run make (I
> want to ensure that PGDATABASE is set):
>
> default: toner
>     env | grep PG
>
> 2) run make .env (if you haven't already)
>
> I think ab49c3f
> <https://github.com/stamen/toner-carto/commit/ab49c3f81330a0a4599b140a08974cc4e2acd0dc>
> may have broken things when I attempted to provide a default w/o requiring
> .env.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/toner-carto/issues/36#issuecomment-123122264>.
>



-- 
Regards,
Jeremy Cimafonte
web. http://www.jeremycimafonte.com
tel. +1(908)463-4387

**Comment by jbcima** [comment]
specific issue is 'FATAL:  database "osm" does not exist'

**Comment by mojodna** [comment]
Aha.  `DATABASE_URL` isn't making it into the environment, I think, which is causing `imposm3` to load data into a non-`toner` database.

**Comment by jbcima** [comment]
ah. when i run 'make .env' this is the .env generated:
DATABASE_URL=postgres:///toner

**Comment by jbcima** [comment]
might as well throw this out there, i'm now redoing from scratch by using db/seattle because before when I was changing the styles or hiding/showing layers and saving the map view wasn't refreshing?? hopefully am able to style and add layers to this one.

**Comment by jbcima** [comment]
did that and was able to successfully generate toner-labels so seems good. let me know if i can be of any help.

**Comment by mojodna** [comment]
Great!

> might as well throw this out there, i'm now redoing from scratch by using db/seattle because before when I was changing the styles or hiding/showing layers and saving the map view wasn't refreshing?? hopefully am able to style and add layers to this one.

Are you using TileMill for this?  There's a small layer of indirection between `toner.yml` and `toner.mml` / `project.mml`.  `make` will convert the YAML file to JSON (`.mml`), so if you're editing the YAML, you'll need to do that before changes will show up.  If you're changing the JSON, those changes will be overwritten when you re-`make`.  Does that make sense?

**Comment by jak2030** [comment]
FWIW I ran into identical problems that were solved by running make .env

**Comment by iambz** [comment]
Hi!
I have the same issue.
Installed everything.

The .env file is there.
`make link`, OK, `make db`, OK.
After that, the database is there and I can connect to it.
`make db/shared` gives me the same errors as @jbcima .

```
psql:sql/functions/highroad.sql:1: NOTICE:  view "highroad_z15plus" does not exist, skipping
psql:sql/functions/highroad.sql:2: NOTICE:  view "highroad_z14" does not exist, skipping
psql:sql/functions/highroad.sql:3: NOTICE:  view "highroad_z13" does not exist, skipping
psql:sql/functions/highroad.sql:4: NOTICE:  view "highroad_z12" does not exist, skipping
psql:sql/functions/highroad.sql:5: NOTICE:  view "highroad_z11" does not exist, skipping
psql:sql/functions/highroad.sql:6: NOTICE:  view "highroad_z10" does not exist, skipping
psql:sql/functions/highroad.sql:26: ERROR:  relation "osm_planet_osm_line_z10" does not exist
LINE 18:       FROM osm_planet_osm_line_z10
                    ^
make: *** [db/functions/highroad] Error 3
```

Any idea from where it could come from? The README doesn't mention anything else before make `db/shared`.

All dependencies installed.
`imposm3 version`: 0.1

**Comment by lerouxb** [comment]
I also had trouble getting things to work on OSX and a combination of these commands did the trick:

```
createdb toner
make .env
```

**Comment by lerouxb** [comment]
Actually it still fails:
```
$ make db/shared
Makefile:659: warning: overriding commands for target `db/ne_10m_admin_1_states_provinces_scale_rank'
Makefile:655: warning: ignoring old commands for target `db/ne_10m_admin_1_states_provinces_scale_rank'
curl -Lf http://data.openstreetmapdata.com/land-polygons-split-3857.zip -o data/osmdata/land_polygons_split.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  453M  100  453M    0     0   740k      0  0:10:26  0:10:26 --:--:--  979k
ERROR:  table "land_polygons" does not exist
```

(and then a gazillion compounding errors)

**Comment by jbcima** [comment]
@stamen-github can you delete this? my phone number is in it for some reason. thanks.

**Comment by almccon** [comment]
> @stamen-github can you delete this? my phone number is in it for some reason. thanks. 

Ok I think I deleted your phone number wherever it was showing up in your email signature.
