### ISSUE TITLE
OSM attribution toner/watercolor is wrong

### ISSUE THREAD

**Issue by jojo4u** [stamen/toner-carto#55]
The attribution on toner/watercolor currently says "Data by Openstreetmap, under CC BY SA". It's ODBL now ;) Terrain says "Data (c) Openstreetmap contributors" which is ok.

**Comment by almccon** [comment]
Thanks for catching that! I'm going to track it in another repo here: https://github.com/stamen/maps.stamen.com/issues/79

You are right that the Toner attribution needs to be updated. However, Watercolor is correct. We've been keeping Watercolor using a very old snapshot of OSM data that dates from before the OSM license change.
