### ISSUE TITLE
How to add a Stamen Toner layer as a base layer in geoserver

### ISSUE THREAD

**Issue by gongenbo** [stamen/toner-carto#61]
http://www.geomesa.org/documentation/tutorials/geomesa-examples-gdelt.html
in the gemesa document i find it use  Stamen Toner as a base layer show in geomesa.
but i don't know how to deployment it, please help me. thanks

**Comment by almccon** [comment]
I'm sorry, I've never used geomesa, so I have no idea. Perhaps there are some geomesa help forums you can ask?

All the information we provide about using Toner can be found at the bottom of the page on http://maps.stamen.com

Thank you for your interest in using Toner!
