### ISSUE TITLE
Falkland Islands  / Islas Malvinas

### ISSUE THREAD

**Issue by HuVas** [stamen/toner-carto#82]
I could understand that the map names are in English. But we can´t use this map because Argentina has an open sovereignty conflict with UK. The name in Spanish is Islas Malvinas. I hope you can understand and correct It, maybe using both names. Thank you. Regrads

**Comment by almccon** [comment]
Duplicate of #19. We will get this fixed when we next deploy the map, but we currently do not have any plans scheduled to refresh the map anytime soon. Sorry!
